---
apiVersion: v1
kind: Service
metadata:
  name: wp-database-service
  labels:
    app: db
    env: dev
    stack: wordpress
spec:
  type: ClusterIP
  ports:
  - port: 80            
    protocol: TCP
    targetPort: 3306      
  selector:
    app: db
    env: dev
    stack: wordpress      