---
apiVersion: v1
kind: Service
metadata:
  name: wp-app-service
  labels:
    app: wp-app
    env: dev
    stack: wordpress
spec:
  type: NodePort
  ports:
  - port: 8888           
    protocol: TCP
    targetPort: 80      
  selector:
    app: wp-app
    env: dev
    stack: wordpress      
